import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { InvoiceResponse } from '../types';
import { formatDate } from './format';

// jsPDF cannot render non-breaking spaces (\u00A0) used by fr-FR locale — outputs "/" instead.
// Use a plain ASCII currency formatter for the PDF only.
function pdfCurrency(amount: number | string | undefined | null): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : (amount ?? 0);
  return num.toLocaleString('en-GB', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }) + ' \u20AC';
}

export function downloadInvoicePdf(invoice: InvoiceResponse): void {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 0, pageW, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('TASKORA', 14, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 14, 28);

  // Invoice number + status (top right)
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.invoiceNumber, pageW - 14, 18, { align: 'right' });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const statusLabel = invoice.status === 'PAYEE' ? 'PAID' : invoice.status === 'ANNULEE' ? 'CANCELLED' : 'PENDING';
  doc.text(statusLabel, pageW - 14, 28, { align: 'right' });

  // ── Meta grid ─────────────────────────────────────────────────────────────
  doc.setTextColor(50, 50, 50);
  doc.setFillColor(248, 249, 252);
  doc.rect(0, 44, pageW, 26, 'F');

  const cols = [
    { label: 'Issued', value: formatDate(invoice.issueDate) },
    { label: 'Due', value: formatDate(invoice.dueDate) },
    { label: 'Project', value: invoice.projectTitle },
    { label: 'Freelancer', value: invoice.userFullName },
  ];
  const colW = pageW / cols.length;
  cols.forEach((col, i) => {
    const x = 14 + i * colW;
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.setFont('helvetica', 'normal');
    doc.text(col.label.toUpperCase(), x, 52);

    doc.setFontSize(9);
    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'bold');
    doc.text(col.value, x, 62);
  });

  // ── Items table ───────────────────────────────────────────────────────────
  autoTable(doc, {
    startY: 78,
    head: [['Description', 'Qty', 'Unit Price', 'Subtotal']],
    body: invoice.lines.map((l) => [
      l.description,
      l.quantity.toString(),
      pdfCurrency(l.unitPrice),
      pdfCurrency(l.subtotal),
    ]),
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [248, 249, 252] },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 20 },
      2: { halign: 'right', cellWidth: 35 },
      3: { halign: 'right', cellWidth: 35 },
    },
    margin: { left: 14, right: 14 },
  });

  // ── Totals ────────────────────────────────────────────────────────────────
  const finalY = (doc as any).lastAutoTable.finalY + 8;
  const totalsX = pageW - 14;
  const labelX = pageW - 80;

  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal HT', labelX, finalY);
  doc.text(pdfCurrency(invoice.totalHT), totalsX, finalY, { align: 'right' });

  doc.text(`TVA (${invoice.taxRate ?? 20}%)`, labelX, finalY + 7);
  doc.text(pdfCurrency(invoice.totalTVA), totalsX, finalY + 7, { align: 'right' });

  // Total TTC row
  doc.setDrawColor(220, 220, 230);
  doc.line(labelX - 2, finalY + 10, totalsX, finalY + 10);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Total TTC', labelX, finalY + 18);
  doc.text(pdfCurrency(invoice.totalTTC), totalsX, finalY + 18, { align: 'right' });

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(160, 160, 160);
  doc.text('Generated by Taskora', pageW / 2, pageH - 10, { align: 'center' });

  doc.save(`${invoice.invoiceNumber}.pdf`);
}
